CREATE TABLE coordinates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    x REAL NOT NULL CHECK (x <= 156 AND x > '-Infinity'::real),
    y INTEGER NOT NULL
);
CREATE TABLE location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    x REAL NOT NULL CHECK (x > '-Infinity'::real AND x < 'Infinity'::real),
    y INTEGER NOT NULL,
    z REAL NOT NULL CHECK (z > '-Infinity'::real AND z < 'Infinity'::real),
    name TEXT NOT NULL
);
CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    eye_color VARCHAR(20) CHECK (eye_color IN ('GREEN', 'BLUE', 'YELLOW', 'WHITE')),
    hair_color VARCHAR(20) CHECK (hair_color IN ('GREEN', 'BLUE', 'YELLOW', 'WHITE')),
    location_id BIGINT NOT NULL REFERENCES location(id),
    weight BIGINT CHECK (weight > 0)
);
CREATE TABLE event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    name TEXT NOT NULL CHECK (name <> ''),
    tickets_count BIGINT NOT NULL CHECK (tickets_count > 0),
    event_type VARCHAR(30) NOT NULL CHECK (event_type IN ('CONCERT', 'BASKETBALL', 'OPERA', 'THEATRE_PERFORMANCE'))
);
CREATE TABLE venue (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    name TEXT NOT NULL CHECK (name <> ''),
    capacity BIGINT CHECK (capacity > 0),
    type VARCHAR(20) NOT NULL CHECK (type IN ('PUB', 'LOFT', 'THEATRE'))
);
CREATE TABLE ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id > 0),
    name TEXT NOT NULL CHECK (name <> ''),
    coordinates_id BIGINT NOT NULL REFERENCES coordinates(id),
    creation_date TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    person_id BIGINT REFERENCES person(id),
    event_id BIGINT NOT NULL REFERENCES event(id),
    price INTEGER NOT NULL CHECK (price > 0),
    type VARCHAR(20) CHECK (type IN ('VIP', 'USUAL', 'CHEAP')),
    discount BIGINT NOT NULL CHECK (discount BETWEEN 1 AND 100),
    number BIGINT CHECK (number > 0),
    venue_id INTEGER NOT NULL REFERENCES venue(id)
);
CREATE INDEX ON ticket(coordinates_id);
CREATE INDEX ON ticket(person_id);
CREATE INDEX ON ticket(event_id);
CREATE INDEX ON ticket(venue_id);
CREATE INDEX ON ticket(name);
CREATE INDEX ON person(location_id);

CREATE FUNCTION count_tickets_venue_greater(p_venue_id INTEGER)
RETURNS BIGINT LANGUAGE plpgsql AS $$
BEGIN
    IF p_venue_id IS NULL OR NOT EXISTS (SELECT 1 FROM venue WHERE id = p_venue_id) THEN
        RAISE EXCEPTION 'Площадка не найдена' USING ERRCODE = 'P0002';
    END IF;
    RETURN (SELECT count(*) FROM ticket WHERE venue_id > p_venue_id);
END;
$$;

CREATE FUNCTION find_tickets_name_prefix(p_prefix TEXT)
RETURNS SETOF ticket LANGUAGE plpgsql AS $$
BEGIN
    IF p_prefix IS NULL THEN
        RAISE EXCEPTION 'Укажите префикс имени' USING ERRCODE = '22023';
    END IF;
    RETURN QUERY SELECT * FROM ticket WHERE starts_with(name, p_prefix) ORDER BY id;
END;
$$;

CREATE FUNCTION find_tickets_venue_less(p_venue_id INTEGER)
RETURNS SETOF ticket LANGUAGE plpgsql AS $$
BEGIN
    IF p_venue_id IS NULL OR NOT EXISTS (SELECT 1 FROM venue WHERE id = p_venue_id) THEN
        RAISE EXCEPTION 'Площадка не найдена' USING ERRCODE = 'P0002';
    END IF;
    RETURN QUERY SELECT * FROM ticket WHERE venue_id < p_venue_id ORDER BY id;
END;
$$;

CREATE FUNCTION sell_ticket(p_ticket_id BIGINT, p_person_id BIGINT, p_amount INTEGER)
RETURNS BIGINT LANGUAGE plpgsql AS $$
BEGIN
    IF p_amount IS NULL OR p_amount <= 0 THEN
        RAISE EXCEPTION 'Сумма продажи должна быть больше 0' USING ERRCODE = '22023';
    END IF;
    IF p_person_id IS NULL OR NOT EXISTS (SELECT 1 FROM person WHERE id = p_person_id) THEN
        RAISE EXCEPTION 'Человек не найден' USING ERRCODE = 'P0002';
    END IF;
    UPDATE ticket SET person_id = p_person_id, price = p_amount WHERE id = p_ticket_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Билет не найден' USING ERRCODE = 'P0002'; END IF;
    RETURN p_ticket_id;
END;
$$;

CREATE FUNCTION clone_ticket_with_discount(p_ticket_id BIGINT, p_discount BIGINT)
RETURNS BIGINT LANGUAGE plpgsql AS $$
DECLARE
    original ticket%ROWTYPE;
    new_price NUMERIC;
    new_id BIGINT;
BEGIN
    IF p_discount IS NULL OR p_discount < 1 OR p_discount > 100 THEN
        RAISE EXCEPTION 'Скидка должна быть от 1 до 100' USING ERRCODE = '22023';
    END IF;
    SELECT * INTO original FROM ticket WHERE id = p_ticket_id FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Билет не найден' USING ERRCODE = 'P0002'; END IF;
    new_price := round(original.price::numeric * (100 + p_discount) / 100);
    IF new_price > 2147483647 THEN
        RAISE EXCEPTION 'Новая цена превышает максимум 2147483647' USING ERRCODE = '22023';
    END IF;
    INSERT INTO ticket(name, coordinates_id, person_id, event_id, price, type, discount, number, venue_id)
    VALUES (original.name, original.coordinates_id, original.person_id, original.event_id,
            new_price::integer, original.type, p_discount, original.number, original.venue_id)
    RETURNING id INTO new_id;
    RETURN new_id;
END;
$$;

COMMIT;

